### ISSUE TITLE
In regards to the readme mentioning a wish to run setup.

### ISSUE THREAD

**Issue by etisdew** [bbenefield89/PythonAlarm#24]
It is very efficient even though we are not using npm to leverage a package.json's "scripts" key to create local aliases and even chain them into a run once scenario.

What options are you exploring?

**Comment by bbenefield89** [comment]
Not much at the moment. My initial thought is to add Pylarm to the users path or possibly insert an alias in their `.bashrc`.

I haven't done any research on this so I'm open for suggestions if you have any.

**Comment by swastikbanerjee07** [comment]
Hey ,I'm not being able to setup Pylarm. This is the error the terminal is showing after I treied to run it after cloning it to my desktop
![screenshot from 2018-10-10 22-37-25](https://user-images.githubusercontent.com/31207633/46753331-31320300-ccdd-11e8-9e69-18052198671c.png)

**Comment by bbenefield89** [comment]
@swastikbanerjee07 that's odd.

First, would you mind creating a new issue for this? A simple copy/paste with an appropriate name will be fine.

Before doing that, try a few things

- Run this from the root directory so that your command will look like `python src/main.py`

- Check your Python version `python --version`, perhaps there's a compatibility problem. Pylarm runs on version `Python 3.7`

- Enter the Python repl from `/src/` with the command `python` and attempt to import the error helper with `from helpers.print_cli_options_error import print_cli_options_error`.

If you still cannot figure this out then of course, feel free to open a new issue following the issue template provided.

**Comment by swastikbanerjee07** [comment]
@bbenefield89 Hi, I'm sorry my terminal was having a compatibility problem. Yes, it's running prefectly fine in python3
